package typegen

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jrvidotti/ddcore/internal/meta"
)

func TestWriteMaterializesEmbeddedSDKsForStandaloneApp(t *testing.T) {
	appDir := t.TempDir()
	reg := meta.NewRegistry()
	if err := reg.Add(&meta.DocType{
		Name:  "Tarefa",
		App:   "exemplo",
		Label: "Tarefa",
		Fields: []*meta.Field{
			{Fieldname: "titulo", Fieldtype: "Data", Label: "Título"},
		},
	}); err != nil {
		t.Fatal(err)
	}

	if err := Write(appDir, reg); err != nil {
		t.Fatal(err)
	}

	for _, rel := range []string{
		".ddcore/types.d.ts",
		".ddcore/sdk/index.ts",
		".ddcore/sdk/test.ts",
		".ddcore/sdk/types.ts",
		".ddcore/desk-sdk/index.ts",
	} {
		if _, err := os.Stat(filepath.Join(appDir, rel)); err != nil {
			t.Errorf("generated file %s: %v", rel, err)
		}
	}

	b, err := os.ReadFile(filepath.Join(appDir, "tsconfig.json"))
	if err != nil {
		t.Fatal(err)
	}
	var cfg struct {
		CompilerOptions struct {
			Paths map[string][]string `json:"paths"`
		} `json:"compilerOptions"`
	}
	if err := json.Unmarshal(b, &cfg); err != nil {
		t.Fatal(err)
	}
	// Relative to the tsconfig.json itself, with no baseUrl: the option was
	// removed in TypeScript 7, where using it is a compile error.
	want := map[string]string{
		"@ddcore/sdk":      "./.ddcore/sdk/index.ts",
		"@ddcore/sdk/test": "./.ddcore/sdk/test.ts",
		"@ddcore/desk-sdk": "./.ddcore/desk-sdk/index.ts",
	}
	for module, path := range want {
		got := cfg.CompilerOptions.Paths[module]
		if len(got) != 1 || got[0] != path {
			t.Errorf("paths[%q] = %v, want [%q]", module, got, path)
		}
	}
}

func TestWritePreservesExistingTSConfig(t *testing.T) {
	appDir := t.TempDir()
	path := filepath.Join(appDir, "tsconfig.json")
	const custom = `{"extends":"./custom.json"}`
	if err := os.WriteFile(path, []byte(custom), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := Write(appDir, meta.NewRegistry()); err != nil {
		t.Fatal(err)
	}
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(b) != custom {
		t.Fatalf("existing tsconfig was overwritten: %s", b)
	}
}

func TestNumericFieldtypesGenerateNumbers(t *testing.T) {
	reg := meta.NewRegistry()
	reg.Add(&meta.DocType{Name: "Session", Module: "Core", Fields: []*meta.Field{
		{Fieldname: "spent", Fieldtype: "Duration"},
		{Fieldname: "score", Fieldtype: "Rating", Options: float64(5)},
		{Fieldname: "notes", Fieldtype: "Text Editor"},
		{Fieldname: "accent", Fieldtype: "Color"},
	}})
	out := Generate(reg)
	for _, want := range []string{"spent: number | null", "score: number | null", "notes: string | null", "accent: string | null"} {
		if !strings.Contains(out, want) {
			t.Errorf("generated types missing %q:\n%s", want, out)
		}
	}
}

func TestTableMultiSelectGeneratesChildRows(t *testing.T) {
	reg := meta.NewRegistry()
	reg.Add(&meta.DocType{Name: "Note Tag", Module: "Core", IsChild: true, Fields: []*meta.Field{
		{Fieldname: "tag", Fieldtype: "Link", Options: "Note"},
	}})
	reg.Add(&meta.DocType{Name: "Note", Module: "Core", Fields: []*meta.Field{
		{Fieldname: "tags", Fieldtype: "Table MultiSelect", Options: "Note Tag"},
	}})
	if out := Generate(reg); !strings.Contains(out, "tags: NoteTag[]") {
		t.Errorf("generated types missing the rows:\n%s", out)
	}
}

// A Geolocation is typed as the GeoJSON it holds. The type is imported only
// when some DocType uses it: an app without one gets the file it always did.
func TestGeolocationImportsItsTypeOnlyWhenUsed(t *testing.T) {
	const plain = "// Generated by `ddcore types` — do not edit.\nimport type { BaseDoc, ChildDoc } from \"@ddcore/sdk\";\n\n"
	reg := meta.NewRegistry()
	reg.Add(&meta.DocType{Name: "Stop", Module: "Core", Fields: []*meta.Field{{Fieldname: "place", Fieldtype: "Data"}}})
	if out := Generate(reg); !strings.HasPrefix(out, plain) {
		t.Fatalf("the header changed for an app without a Geolocation:\n%s", out)
	}
	reg.Add(&meta.DocType{Name: "Zone", Module: "Core", Fields: []*meta.Field{{Fieldname: "area", Fieldtype: "Geolocation"}}})
	out := Generate(reg)
	if !strings.Contains(out, "import type { BaseDoc, ChildDoc, GeoFeatureCollection } from \"@ddcore/sdk\";\n") ||
		!strings.Contains(out, "area: GeoFeatureCollection | null;") {
		t.Fatalf("the Geolocation is not typed:\n%s", out)
	}
}
