package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// Image is the official image a site's Dockerfile starts from, published by
// the release workflow for every tagged version.
const Image = "ghcr.io/jrvidotti/ddcore"

// Docker writes the files that build a site's production image: a Dockerfile
// on the official image at tag, and a .dockerignore. tag is the release the
// site pins (`0.21.0`); empty, for a binary that is not a release, writes
// `latest` with a note to pin it. A file that already exists is left alone.
// It returns the files it wrote.
func Docker(dir, tag string) ([]string, error) {
	return writeNew(dir, []struct{ name, content string }{
		{"Dockerfile", dockerfile(tag)},
		{".dockerignore", dockerignore},
	})
}

// Railway writes railway.json: build the Dockerfile, gate a deploy on
// /api/ready, restart on failure. The Dockerfile itself comes from Docker.
func Railway(dir string) ([]string, error) {
	return writeNew(dir, []struct{ name, content string }{{"railway.json", railwayJSON}})
}

func writeNew(dir string, files []struct{ name, content string }) ([]string, error) {
	var written []string
	for _, f := range files {
		path := filepath.Join(dir, f.name)
		if _, err := os.Stat(path); err == nil {
			continue
		}
		if err := os.WriteFile(path, []byte(f.content), 0o644); err != nil {
			return written, err
		}
		written = append(written, f.name)
	}
	return written, nil
}

func dockerfile(tag string) string {
	pin := "# The tag is the ddcore release this site runs: keep it inside the \"ddcore\"\n" +
		"# range of ddcore.json, and change both in the same commit.\n"
	if tag == "" {
		tag = "latest"
		pin = "# Pin a release here (`" + Image + ":0.21.0`) before going to production —\n" +
			"# latest moves under you — and keep it inside the \"ddcore\" range of ddcore.json.\n"
	}
	return fmt.Sprintf(`# syntax=docker/dockerfile:1
# This site's production image: the official ddcore image, which brings the
# binary, pg_dump for backups and the timezone data, with the site on top.
%sFROM %s:%s

COPY ddcore.json ./
COPY apps/ ./apps/

# The base image does the rest: WORKDIR /app, uploads and local backups in
# /data (mount a volume there, or set DDCORE_STORAGE=s3), $PORT honoured, and
# CMD ["ddcore", "start"], which migrates before it serves.
`, pin, Image, tag)
}

const dockerignore = `.git
.env
.claude
.worktrees
# uploaded files and local backups: the running site's, not the image's
data/
node_modules/
# typings generated by migrate and types; the server does not read them
**/.ddcore
*.log
docker-compose.yml
`

const railwayJSON = `{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "dockerfilePath": "Dockerfile"
  },
  "deploy": {
    "healthcheckPath": "/api/ready",
    "healthcheckTimeout": 300,
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 5
  }
}
`

// RailwayVariables is what `ddcore deploy railway` tells the operator to set
// on the service: the platform cannot guess any of them, and the site will
// not work — or not safely — without them.
const RailwayVariables = `Set on the Railway service (Variables):
  DATABASE_URL=${{Postgres.DATABASE_URL}}   after adding a PostgreSQL service
  DDCORE_URL=https://<the service's domain>  recovery and invitation links
  DDCORE_TRUST_PROXY=true                    Railway's proxy sets X-Forwarded-For
  DDCORE_ADMIN_PASSWORD=<a strong password>  Admin's first password (never shown in the log)
  DDCORE_SECRET_KEY=<openssl rand -hex 32>   encrypted Vault fields and webhook signing
  DDCORE_SECRET_*                            each secret the apps read (see .env.example)
Uploads: attach a volume at /data, or set DDCORE_STORAGE=s3 and DDCORE_S3_*.
A volume ties the service to one replica; run several only with S3 storage.
`
