package scaffold

import (
	"fmt"
	"os"
	"path/filepath"
)

// Image is the official image a site's Dockerfile starts from, published by
// the release workflow for every tagged version.
const Image = "ghcr.io/jrvidotti/ddcore"

// Docker writes the files that build a site's production image: a Dockerfile
// on the official image at tag, and a .dockerignore. tag is the minor series
// the site follows (`0.21`); empty, for a binary that is not a release, writes
// `latest` with a note to pin it. A file that already exists is left alone.
// It returns the files it wrote.
func Docker(dir, tag string) ([]string, error) {
	return writeNew(dir, []struct{ name, content string }{
		{"Dockerfile", dockerfile(tag)},
		{".dockerignore", dockerignore},
	})
}

// RailwaySite is what `.railway/railway.ts` needs to know about the site.
type RailwaySite struct {
	Name   string // the Railway project and service name
	Repo   string // owner/repo on GitHub, from the checkout's origin; empty when unknown
	Branch string // the branch a push to which deploys
}

// Railway writes the site's Railway project as Infrastructure as Code —
// `.railway/railway.ts`, applied with `railway config plan` / `apply` — and
// the package.json that brings its SDK. The legacy railway.json is not
// written: Railway stops reading it on 2026-12-01.
func Railway(dir string, site RailwaySite) ([]string, error) {
	if err := os.MkdirAll(filepath.Join(dir, ".railway"), 0o755); err != nil {
		return nil, err
	}
	return writeNew(dir, []struct{ name, content string }{
		{filepath.Join(".railway", "railway.ts"), railwayTS(site)},
		{filepath.Join(".railway", "package.json"), railwayPackageJSON},
	})
}

func writeNew(dir string, files []struct{ name, content string }) ([]string, error) {
	var written []string
	for _, f := range files {
		path := filepath.Join(dir, f.name)
		if _, err := os.Stat(path); err == nil {
			continue
		}
		if err := os.WriteFile(path, []byte(f.content), 0o644); err != nil {
			return written, err
		}
		written = append(written, f.name)
	}
	return written, nil
}

func dockerfile(tag string) string {
	pin := "# The tag is the ddcore minor series this site runs: each deploy takes its\n" +
		"# newest patch. Keep it inside the \"ddcore\" range of ddcore.json and move\n" +
		"# both in the same commit; `:" + tag + ".N` pins one exact release instead.\n"
	if tag == "" {
		tag = "latest"
		pin = "# Pin a minor series here (`" + Image + ":0.21`) before going to production —\n" +
			"# latest moves to the next minor, which may break — and keep it inside the\n" +
			"# \"ddcore\" range of ddcore.json.\n"
	}
	return fmt.Sprintf(`# syntax=docker/dockerfile:1
# This site's production image: the official ddcore image, which brings the
# binary, pg_dump for backups and the timezone data, with the site on top.
%sFROM %s:%s

COPY ddcore.json ./
COPY apps/ ./apps/

# The base image does the rest: WORKDIR /app, uploads and local backups in
# /data (mount a volume there, or set DDCORE_STORAGE=s3), $PORT honoured, and
# CMD ["ddcore", "start"], which migrates before it serves.
`, pin, Image, tag)
}

const dockerignore = `.git
.env
.claude
.worktrees
# the Railway project as code, applied from a checkout, not built into the image
.railway
# uploaded files and local backups: the running site's, not the image's
data/
node_modules/
# typings generated by migrate and types; the server does not read them
**/.ddcore
*.log
docker-compose.yml
`

func railwayTS(site RailwaySite) string {
	source := "    // source: github(\"owner/repo\", { branch: \"main\" }), // the repository a push to which deploys\n"
	imports := "defineRailway, postgres, preserve, project, service"
	if site.Repo != "" {
		branch := site.Branch
		if branch == "" {
			branch = "main"
		}
		source = fmt.Sprintf("    // every push to %s deploys\n    source: github(%q, { branch: %q }),\n", branch, site.Repo, branch)
		imports = "defineRailway, github, postgres, preserve, project, service"
	}
	return fmt.Sprintf(`import { %s } from "railway/iac";

// The Railway project this ddcore site deploys to: the site, built from its
// Dockerfile, and its PostgreSQL. `+"`railway config plan`"+` previews a change and
// `+"`railway config apply`"+` makes it, once the SDK is installed
// (`+"`npm install --prefix .railway`"+`). Secrets never live here: preserve() keeps
// the value set in Railway, where each one is entered.
export default defineRailway(() => {
  const db = postgres("Postgres");

  const site = service(%q, {
%s    // the image migrates before it serves, so readiness gates a deploy on a
    // schema that applied; a failed one leaves the previous deployment serving
    healthcheck: "/api/ready",
    healthcheckTimeout: 300,
    env: {
      DATABASE_URL: db.env.DATABASE_URL,
      DDCORE_TRUST_PROXY: "true", // Railway's proxy sets X-Forwarded-For
      DDCORE_URL: preserve(), // https://<the site's domain>: recovery and invitation links
      DDCORE_ADMIN_PASSWORD: preserve(), // Admin's first password, never shown in the log
      DDCORE_SECRET_KEY: preserve(), // openssl rand -hex 32: Vault fields, webhook signing
      // and each DDCORE_SECRET_* the apps read, as preserve()
    },
    // Uploads: a volume at /data, which keeps the site at one replica —
    //   volumeMounts: { "/data": volume(%q) },
    // or a bucket (DDCORE_STORAGE: "s3" and the DDCORE_S3_* variables).
    // domains: ["erp.example.com"],
  });

  return project(%q, {
    resources: [db, site],
  });
});
`, imports, site.Name, source, site.Name+"-data", site.Name)
}

// railwayPackageJSON brings the SDK railway.ts imports. It lives in .railway,
// not at the site's root, so the site itself stays free of Node.
const railwayPackageJSON = `{
  "name": "railway-config",
  "private": true,
  "devDependencies": {
    "railway": "^3.11.0"
  }
}
`

// RailwayNext is what `ddcore deploy railway` tells the operator to do next.
const RailwayNext = `Next:
  1. npm install --prefix .railway            the SDK railway.ts imports
  2. railway link                              the project (railway init creates one)
  3. set the secrets in Railway's Variables:   DDCORE_URL, DDCORE_ADMIN_PASSWORD,
     DDCORE_SECRET_KEY and each DDCORE_SECRET_* the apps read (see .env.example)
  4. railway config plan, then railway config apply
Uploads: a volume at /data (one replica), or DDCORE_STORAGE=s3 and DDCORE_S3_* (any number).
`
