package scaffold

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ProjectInfo is what `ddcore init` knows about the site it creates, which the
// README repeats so its instructions are the ones that work on this project.
type ProjectInfo struct {
	Name    string // the project, and the local database's name
	DSN     string
	Port    int
	Compose bool // a docker-compose.yml was written next to ddcore.json
}

// Project writes the files a new site needs besides ddcore.json: the guide
// for coding agents (AGENTS.md, with CLAUDE.md pointing at it), the MCP
// configuration, a .gitignore and a README. A file that already exists is left
// alone. It returns the files it wrote.
func Project(dir string, p ProjectInfo) ([]string, error) {
	var written []string
	for _, f := range []struct{ name, content string }{
		{"AGENTS.md", agentsMD},
		{".mcp.json", mcpJSON},
		{".gitignore", gitignore},
		{"README.md", readme(p)},
	} {
		path := filepath.Join(dir, f.name)
		if _, err := os.Stat(path); err == nil {
			continue
		}
		if err := os.WriteFile(path, []byte(f.content), 0o644); err != nil {
			return written, err
		}
		written = append(written, f.name)
	}
	claude := filepath.Join(dir, "CLAUDE.md")
	if _, err := os.Lstat(claude); errors.Is(err, os.ErrNotExist) {
		// Claude Code reads CLAUDE.md, every other agent AGENTS.md: one file,
		// two names. Where a symlink cannot be made, an import does the same.
		if err := os.Symlink("AGENTS.md", claude); err != nil {
			if err := os.WriteFile(claude, []byte("@AGENTS.md\n"), 0o644); err != nil {
				return written, err
			}
		}
		written = append(written, "CLAUDE.md")
	}
	return written, nil
}

const mcpJSON = `{
  "mcpServers": {
    "ddcore": { "command": "ddcore", "args": ["mcp"] }
  }
}
`

const gitignore = `# secrets and per-machine settings; .env.example is the committed template
.env
# generated by ddcore migrate / ddcore types
.ddcore/
# uploaded files and local backups (dataDir)
data/
node_modules/
*.log
`

const agentsMD = "# Guidelines for coding agents\n\n" +
	"This is a **ddcore** site: apps written as TypeScript DocTypes, run by the `ddcore` binary\n" +
	"(Go) on PostgreSQL. `ddcore.json` lists the apps it loads, under `apps/`.\n\n" +
	"## Start here\n\n" +
	"- The reference ships inside the binary: read the MCP resource `ddcore://docs/index`\n" +
	"  (or run `ddcore docs`) before writing code. `ddcore://changelog` and the `whats_new` tool\n" +
	"  say what changed in the running version.\n" +
	"- Prefer the ddcore MCP tools (`.mcp.json` starts `ddcore mcp`) to touching the database:\n" +
	"  `get_doctype` / `scaffold_doctype` → `migrate` → `insert_doc` / `list_docs` → `run_tests`.\n" +
	"- The database must be running (`docker compose up -d`) for the CLI and MCP to work.\n\n" +
	"## Layout of an app (`apps/<app>/`)\n\n" +
	"- `ddcore.app.ts` — `defineApp`: name, title, version, `ddcore` range, roles, scheduler, docEvents.\n" +
	"- `doctypes/<snake>/<snake>.doctype.ts` — meta (`defineDoctype`). Fieldnames in snake_case ASCII.\n" +
	"- `doctypes/<snake>/<snake>.controller.ts` — rules (`defineController`): validate, onSubmit, methods.\n" +
	"- `doctypes/<snake>/<snake>.form.ts` — desk script (`defineForm`), runs in the browser.\n" +
	"- `doctypes/<snake>/<snake>.test.ts` — tests (`ddcore test`); each `it` runs in a rolled-back transaction.\n" +
	"- `services/*.ts` — business functions; export with `whitelisted()` to expose them at\n" +
	"  `/api/method/<app>.services.<file>.<fn>`.\n" +
	"- `reports/*.report.ts`, `workspaces/*.workspace.ts`, `patches/NNNN_*.ts`, `translations/<lang>.csv`.\n\n" +
	"## Commands\n\n" +
	"- `ddcore dev` — server with hot reload and auto-migrate; do not start a second one.\n" +
	"- `ddcore migrate --dry-run` / `ddcore migrate` — apply the schema the DocTypes declare.\n" +
	"- `ddcore test [--app name]` — run the `*.test.ts` files.\n" +
	"- `ddcore types` — regenerate the typings; `ddcore eval '<ts>'` — run loose TypeScript.\n" +
	"- `ddcore i18n extract --all --check` — every label must have its translation.\n" +
	"- `ddcore doctor` — what is wrong with the site, and whether the binary is out of date.\n\n" +
	"## Rules\n\n" +
	"1. **Server code is synchronous.** Controllers and services run in goja: no `await`, no\n" +
	"   Node APIs. Desk scripts (`@ddcore/desk-sdk`) run in the browser and may be async.\n" +
	"2. **Never edit `.ddcore/`.** `ddcore migrate` and `ddcore types` regenerate it.\n" +
	"3. **English strings are keys.** Write every label and Select value in English and translate\n" +
	"   it in `translations/<lang>.csv` with `ddcore i18n extract`.\n" +
	"4. **Never call commit.** A request, a job or a test is one transaction the framework owns.\n" +
	"5. `mandatoryDependsOn` and permissions are enforced on the server; the desk only mirrors them.\n" +
	"6. Validate a change with `ddcore test` before calling it done.\n"

func readme(p ProjectInfo) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", p.Name)
	b.WriteString("A [ddcore](https://ddcore.dev) site: apps written as TypeScript DocTypes, run by the\n`ddcore` binary on PostgreSQL.\n\n")
	b.WriteString("## Requirements\n\n")
	b.WriteString("- The ddcore CLI:\n\n  ```bash\n  curl -fsSL https://raw.githubusercontent.com/jrvidotti/ddcore/main/install.sh | sh\n  ddcore version\n  ```\n\n")
	if p.Compose {
		b.WriteString("- [Docker](https://docs.docker.com/get-docker/) with Compose, for the database.\n\n")
	} else {
		b.WriteString("- PostgreSQL 14+, reachable at the `dsn` in `ddcore.json`.\n\n")
	}
	b.WriteString("## Setup\n\n```bash\n")
	if p.Compose {
		b.WriteString("docker compose up -d                              # PostgreSQL, see docker-compose.yml\n")
	}
	b.WriteString("cp .env.example .env                              # optional: per-machine settings and secrets\n")
	b.WriteString("ddcore migrate                                    # creates the tables and prints the Admin password\n")
	b.WriteString("ddcore dev                                        # hot reload\n```\n\n")
	fmt.Fprintf(&b, "Open <http://localhost:%d> and sign in as `Admin` with the password `ddcore migrate` printed.\n"+
		"Change it with `ddcore user passwd Admin <password>`.\n\n", p.Port)
	fmt.Fprintf(&b, "The site connects to `%s` (`dsn` in `ddcore.json`). ", p.DSN)
	b.WriteString("To use another database on one machine, set `DDCORE_DSN` in `.env` instead of editing `ddcore.json`.\n")
	if p.Compose {
		b.WriteString("`docker compose down` stops the database, and `docker compose down -v` also deletes its data.\n")
	}
	b.WriteString("\n## Development\n\n")
	b.WriteString("| Command | What it does |\n| --- | --- |\n")
	b.WriteString("| `ddcore new-app <name>` | scaffolds `apps/<name>` and registers it in `ddcore.json` |\n")
	b.WriteString("| `ddcore dev` | server with hot reload; applies schema changes as files are saved |\n")
	b.WriteString("| `ddcore migrate [--dry-run]` | applies (or shows) the schema the DocTypes declare |\n")
	b.WriteString("| `ddcore test [--app name]` | runs the `*.test.ts` files, each test rolled back |\n")
	b.WriteString("| `ddcore i18n extract --all` | updates `translations/<lang>.csv` from the code |\n")
	b.WriteString("| `ddcore doctor` | checks the database, pending migrations, queue and binary version |\n")
	b.WriteString("| `ddcore docs [name]` | the framework reference, offline |\n\n")
	b.WriteString("## Coding agents and MCP\n\n")
	b.WriteString("`ddcore mcp` is an [MCP](https://modelcontextprotocol.io) server with this site's metadata, the\n")
	b.WriteString("framework reference (`ddcore://docs/*`) and tools to scaffold DocTypes, migrate, query and run\n")
	b.WriteString("tests. `.mcp.json` already registers it, so Claude Code offers it when this folder is opened;\n")
	b.WriteString("other clients take the same command:\n\n")
	b.WriteString("```json\n{ \"mcpServers\": { \"ddcore\": { \"command\": \"ddcore\", \"args\": [\"mcp\"] } } }\n```\n\n")
	fmt.Fprintf(&b, "While `ddcore dev` runs, the same server answers over HTTP at `http://localhost:%d/mcp`, for\n", p.Port)
	b.WriteString("an Admin API key (`ddcore apikey Admin`) sent as `Authorization: token key:secret`.\n\n")
	b.WriteString("The conventions an agent must follow are in [`AGENTS.md`](AGENTS.md) (`CLAUDE.md` points at it).\n\n")
	b.WriteString("## Layout\n\n```\n")
	b.WriteString("ddcore.json          the site: database, port, apps, language, currency (committed)\n")
	b.WriteString(".env.example         the environment variables a deployment can set (copy to .env)\n")
	if p.Compose {
		b.WriteString("docker-compose.yml   PostgreSQL for development\n")
	}
	b.WriteString("apps/<name>/         one directory per app: doctypes, services, reports, translations\n")
	b.WriteString("AGENTS.md            guidelines for coding agents\n```\n\n")
	b.WriteString("## Deployment\n\n")
	b.WriteString("See the [deployment guide](https://ddcore.dev/guide/deployment): the binary, the `apps/`\n")
	b.WriteString("directory, `ddcore.json` and a PostgreSQL database, with secrets in the environment.\n")
	return b.String()
}
